from enum import Enum


# TODO use real DB

class GenrePriority(Enum):
    NEVER = 0
    MAYBE = 1
    ALWAYS = 2


MOCK_DB = {
    'genres': {
        'hip hop': GenrePriority.ALWAYS,
        'rap': GenrePriority.ALWAYS,
        'atl hip hop': GenrePriority.ALWAYS,
        'r&b': GenrePriority.ALWAYS,
        'cloud rap': GenrePriority.ALWAYS,
        'aesthetic rap': GenrePriority.ALWAYS,
        'trap': GenrePriority.ALWAYS,
        'viral rap': GenrePriority.ALWAYS,
        'southern hip hop': GenrePriority.ALWAYS,
        'alt z': GenrePriority.ALWAYS,
        'emo rap': GenrePriority.ALWAYS,
        'ottawa rap': GenrePriority.ALWAYS,
        'alternative r&b': GenrePriority.ALWAYS,
        'chicago rap': GenrePriority.ALWAYS,
        'uk drill': GenrePriority.ALWAYS,
        'glitchcore': GenrePriority.ALWAYS,
        'new orleans rap': GenrePriority.ALWAYS,
        'kentucky hip hop': GenrePriority.ALWAYS,
        'uk hip hop': GenrePriority.ALWAYS,
        'viral trap': GenrePriority.ALWAYS,
        'cali rap': GenrePriority.ALWAYS,
        'new york drill': GenrePriority.ALWAYS,
        'pittsburgh rap': GenrePriority.ALWAYS,
        'rap francais': GenrePriority.ALWAYS,
        'philly rap': GenrePriority.ALWAYS,
        'zxc': GenrePriority.ALWAYS,
        'trap soul': GenrePriority.ALWAYS,
        'melodic drill': GenrePriority.ALWAYS,
        'french hip hop': GenrePriority.ALWAYS,
        'german cloud rap': GenrePriority.ALWAYS,
        'nyc rap': GenrePriority.ALWAYS,
        'tennessee hip hop': GenrePriority.ALWAYS,
        'pop rap': GenrePriority.ALWAYS,
        'deep underground hip hop': GenrePriority.ALWAYS,
        'scream rap': GenrePriority.ALWAYS,
        'canadian trap': GenrePriority.ALWAYS,
        'london rap': GenrePriority.ALWAYS,
        'manchester hip hop': GenrePriority.ALWAYS,
        'cloud rap francais': GenrePriority.ALWAYS,
        'underground hip hop': GenrePriority.ALWAYS,
        'canadian hip hop': GenrePriority.ALWAYS,
        'miami hip hop': GenrePriority.ALWAYS,
        'new jersey rap': GenrePriority.ALWAYS,
        'german trap': GenrePriority.ALWAYS,
        'melodic rap': GenrePriority.ALWAYS,
        'chill drill': GenrePriority.ALWAYS,
        'rap latina': GenrePriority.ALWAYS,
        'belgian hip hop': GenrePriority.ALWAYS,
        'german hip hop': GenrePriority.ALWAYS,
        'bedroom r&b': GenrePriority.ALWAYS,
        'florida rap': GenrePriority.ALWAYS,
        'pop urbaine': GenrePriority.ALWAYS,
        'drift phonk': GenrePriority.ALWAYS,
        'rage rap': GenrePriority.ALWAYS,
        'dark trap': GenrePriority.ALWAYS,
        'j-pop': GenrePriority.MAYBE,
        'new wave': GenrePriority.MAYBE,
        'dirty south rap': GenrePriority.MAYBE,
        'old school atlanta hip hop': GenrePriority.MAYBE,
        'alternative hip hop': GenrePriority.MAYBE,
        'j-rock': GenrePriority.MAYBE,
        'neo soul': GenrePriority.MAYBE,
        'memphis hip hop': GenrePriority.MAYBE,
        'psychedelic pop': GenrePriority.MAYBE,
        'sacramento hip hop': GenrePriority.MAYBE,
        'r&drill': GenrePriority.MAYBE,
        'rap lyonnais': GenrePriority.MAYBE,
        'brooklyn drill': GenrePriority.MAYBE,
        'drill francais': GenrePriority.MAYBE,
        'ohio hip hop': GenrePriority.MAYBE,
        'german drill': GenrePriority.MAYBE,
        'rap belge': GenrePriority.MAYBE,
        'dutch drill': GenrePriority.MAYBE,
        'indie hip hop': GenrePriority.MAYBE,
        'aussie drill': GenrePriority.MAYBE,
        'philly drill': GenrePriority.MAYBE,
        'trap queen': GenrePriority.MAYBE,
        'drill': GenrePriority.MAYBE,
        'political hip hop': GenrePriority.NEVER,
        'pov: indie': GenrePriority.NEVER,
        'country': GenrePriority.NEVER,
        'classic oklahoma country': GenrePriority.NEVER,
        'pixel': GenrePriority.NEVER,
        'contemporary country': GenrePriority.NEVER,
        'show tunes': GenrePriority.NEVER,
        'otacore': GenrePriority.NEVER,
        'country road': GenrePriority.NEVER,
        'broadway': GenrePriority.NEVER,
        'sierreno': GenrePriority.NEVER,
        'dc indie': GenrePriority.NEVER,
        'singer-songwriter pop': GenrePriority.NEVER,
        'lds youth': GenrePriority.NEVER,
        'new romantic': GenrePriority.NEVER,
        'dance pop': GenrePriority.NEVER,
        'singer-songwriter': GenrePriority.NEVER,
        'country rock': GenrePriority.NEVER,
        'outlaw country': GenrePriority.NEVER,
        'corridos tumbados': GenrePriority.NEVER,
        'album rock': GenrePriority.NEVER,
        'rock': GenrePriority.NEVER,
        'hollywood': GenrePriority.NEVER,
        'nashville sound': GenrePriority.NEVER,
        'movie tunes': GenrePriority.NEVER,
        'classic country pop': GenrePriority.NEVER,
        'conscious hip hop': GenrePriority.NEVER,
        'sad sierreno': GenrePriority.NEVER,
        'dance rock': GenrePriority.NEVER,
        'classic texas country': GenrePriority.NEVER,
        'europop': GenrePriority.NEVER,
        'colombian pop': GenrePriority.NEVER,
        'synthpop': GenrePriority.NEVER,
        'indie r&b': GenrePriority.NEVER,
        'new wave pop': GenrePriority.NEVER,
        'corrido': GenrePriority.NEVER,
        'soft rock': GenrePriority.NEVER,
        'soul flow': GenrePriority.NEVER,
        'lgbtq+ hip hop': GenrePriority.NEVER,
        'edm': GenrePriority.NEVER,
        'electro house': GenrePriority.NEVER,
        'hyperpop': GenrePriority.NEVER,
        'german hyperpop': GenrePriority.NEVER,
        'electronic trap': GenrePriority.NEVER,
        'proto-hyperpop': GenrePriority.NEVER,
        'meme rap': GenrePriority.NEVER,
        'meme': GenrePriority.NEVER,
    },
    # all previously encountered tracks which either only had genres of priority 'NEVER' or were uploaded to YouTube
    'tracks': {
        '5v3MSh7CD3VNyCwAoSha5p',
    },
}
